services:
  odoo:
    image: odoo:17.0
    depends_on:
      - db
    ports:
      - "8069:8069"
    volumes:
      - ./config:/etc/odoo
      - ./enterprise17:/mnt/extra-addons
    networks:
      - odoo
    environment:
    - HOST=db
    - PORT=5432
    - USER=odoo
    - PASSWORD=odoo
  db:
    image: postgres:15
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_PASSWORD=odoo
      - POSTGRES_USER=odoo
    ports:
      - "5435:5432"
    networks:
      - odoo

networks:
  odoo: {}

volumes:
  odoo:
